### ISSUE TITLE
Hello! Can the diffCD loss be directly applied to two corresponding clusters of point clouds?

### ISSUE THREAD

**Issue by git-guocc** [Linusnie/diffcd#1]
Hello! Can the diffCD loss be directly applied to two corresponding clusters of point clouds?

**Comment by Linusnie** [comment]
Hi, I'm not sure I understand the question. But if there are multiple clusters in the input point cloud the method should still work

**Comment by git-guocc** [comment]
Thank you for your reply! I have a question regarding Equation (10) in the paper. It seems that this formula doesn't compute the distance directly between two point clouds like the Chamfer Distance (CD) does. Instead, it involves sampling from the implicit surface. Could you clarify if there's a way to adapt this formula to directly compare two point clouds without surface sampling? I'm looking for a loss function that works more similarly to CD, where the point clouds are directly compared.

**Comment by Linusnie** [comment]
I see! DiffCD is inherently a method that minimizes the distance between a point cloud and an implicit surface, so it is not really suitable for matching two point clouds. Something like iterative closest point might make more sense in your case
